### ISSUE TITLE
hnFirebase code comments

### ISSUE THREAD

**Issue by stkao05** [vlod/sample-code#1]
Hi @vlod 
I think the hnFirebase code could be improved if async/await is not used. One main issue is that the codes is fetching each HN post item iteratively one at the time. The codes could be made more concurrent if it was written as:

```
function getItems(items) {
  const results = [];

  // to save time, don't bother processing all the items for now
  for (const item of items.slice(0, MAX_POSTS)) {
    const post = getItem(item);
    results.push(post);
  }

  return Promise.all(results);
}
```

**Comment by vlod** [comment]
Thanks for the feedback.

Yes.. you're right. I came to the same conclusion on my first iteration.

However :) if you remove the .slice() above, you'll find there are 400 items (I believe) that will run concurrently). I thought that was too much for my server and the hosting server. Of course firebase could probably handle it, but I was trying to create generic code that could process a queue of 'stuff', do a network connection and process the results.

What I was really trying to find was a way to do async.queue() from async library: https://caolan.github.io/async/docs.html#queue but for promises.

I really want to only handle maybe 10 concurrent connections.

Have you seen such a thing?

**Comment by vlod** [comment]
I think something like this might work:
https://github.com/digitaltsai/simple-promise-queue

**Comment by stkao05** [comment]
Hi vlog,

Removing `slice();` won't turn the async/await codes concurrent; it only makes the items array shorter.

The main issue with the current `async/await` code is that the codes is blocked on every await call. Hence, each request is made sequentially instead of concurrently.

```
// async/await
for (const item of items) {
    // this line is blocking the execution of next code line
    // until the request is completed.
    const post = await getItem(item);
    results.push(post);
}
```

You don't really need a `async.queue()` library to make your codes concurrent; Removing the async/await will simply do.

I have run the codes with `slice()` removed. The current async/await version take 114280 ms, whereas the codes without async/await took 4036 ms.

**Comment by stkao05** [comment]
Hi @vlod,

Removing `slice();` won't turn the async/await codes concurrent; it only makes the items array shorter.

When this line code is called:

```
firebase.app().database().ref(`v0/item/${item}`).once("value")
```

Network request will be initiated, but the codes won't block and wait util the receiving the response. That is why it returns a `Promise()` object, and the next line of codes could be immediately executed. Network call in most JS (nodesjs/browser) is already concurrent by nature. If you call two API calls 

```
firebase.app().database().ref(`v0/item/1`).once("value")
firebase.app().database().ref(`v0/item/2`).once("value")
```

Two API requests will happen concurrently.

The main issue with the current code is that the `await` line will wait until the Promise is resolve (which in scenario, is when receiving API response). Therefore each request is made sequentially instead of concurrently.

```
await firebase.app().database().ref(`v0/item/1`).once("value")

// this line of code won't execute until API returned.
await firebase.app().database().ref(`v0/item/2`).once("value")
```

You don't really need a `async.queue()` library to make your codes concurrent; removing the async/await will simply do. 

To give the perspective of its actual performance, I have run the codes with `slice()` removed. The current async/await version take 114280 ms, whereas the codes without async/await took 4036 ms.

**Comment by vlod** [comment]
I understand that using 'await' will turn the code into sequential access rather than concurrent access and it has nothing to do with removing slice(). I realize that await will block until the promise is resolved. I know that I don't need async.queue() library to make this code concurrent.

My first iteration of this code, did NOT have 'await' and was fully concurrent (as you're suggesting)

I agree with what you're saying! :) 

However as I mentioned above, the concern I have is hitting the remote server with 500 concurrent hits within (~ 4036ms). The concern is *load* not the ability to do this concurrently.

In this example, let's assume instead of 500 items, we had 10,000 items. Hitting a remote server with 10,000 concurrency requests (in that short period of time ~4secs) is at best not polite and at worse will either crash the server or mostly hit a rate-limit block.

Any thoughts of how you would handle if the items count was 100K or 1M? 

My solution, (I've updated the code) to use a promise-queue library. It will only run 20 concurrent promises (configurable) and not overload the remote (and local) server. I could have an item count of 10K or 10M items and it would still have the same load.

**Comment by vlod** [comment]
i.e. If you have a list of 100K requests to do, how do you limit the number of concurrent requests (to a remote sever) to say 20 total, rather than 100K? My solution is to use a promise-queue library.

I would love to know if you have any ideas on how to limit the number of simultaneous concurrencies occurring.

**Comment by stkao05** [comment]
Ah I see! Sorry I misunderstood your previous comment. Now it makes much more sense to me about what you were trying to do before.

Indeed `async/await` will make it easier to achieve the goal, and I think a queue library is also a good tool for this task.

Just for fun I also tried to write a solution with `async/await` 

```
async function getItems(items, concurrency) {
  const results = [];
  const pending = new Set();

  const process = (item) => {
    const p = getItem(item).then((post) => {
        pending.delete(p);
        return post;
    }).catch(() => {
        pending.delete(p);
        return null;
    });
    results.push(p)
    pending.add(p)
  }

  for (const item of items) {
    if (pending.size < concurrency) {
        process(item);
    } else {
        await Promise.race(pending.values());
        process(item);
    }
  }

  await Promise.all(pending.values());
  return (await Promise.all(results)).filter((p) => p);
}
```

Great to have this discussion with you; it was fun brainstorming exercise :)

**Comment by vlod** [comment]
> Great to have this discussion with you; it was fun brainstorming exercise :)

Indeed! Thanks for the code and the great discussion!
